### ISSUE TITLE
"list" replaced with "name", "name" replaced with "key" 

### ISSUE THREAD

**Issue by lorenzo95** [Fluent-networks/tailscale-mikrotik#1]
Just a heads-up on the changes in 7.4. When you thought the fun wouldn't stop ;)

This won't work anymore
/container/envs
add list="tailscale" name="AUTH_KEY" value="tskey-xxxxxxxxxxxxxxxxxxxxxxxx"
add list="tailscale" name="ADVERTISE_ROUTES" value="192.168.88.0/24"
add list="tailscale" name="CONTAINER_GATEWAY" value="172.17.0.1"

It now reads like this for example
/container/envs
add name="tailscale" key="AUTH_KEY" value="tskey-xxxxxxxxxxxxxxxxxxxxxxxx"
add name="tailscale" key="ADVERTISE_ROUTES" value="192.168.88.0/24"
add name="tailscale" key="CONTAINER_GATEWAY" value="172.17.0.1"

Registries are supported now as-well. Making it easier to keep updated from docker hub.

Cheers

**Comment by frankedwards** [comment]
Hi

Yes, thanks - strangely on my router running 7.4beta4 the older syntax seems to work. Perhaps this is to do with an upgrade from factory v6 to v7?

I'll update the README to reflect the official Container documentation.

Regards

Frank
