### ISSUE TITLE
How to active and use SOCKS5 or HTTP proxy with this container?

### ISSUE THREAD

**Issue by vuducdong** [Fluent-networks/tailscale-mikrotik#12]
I have successfully installed Tailscale on the Mikrotik Router, but don't see an option to enable SOCKS5 or HTTP proxy. Please help. Thank you!

And how can I download *.tar file to my computer, I use Windows PC
![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/74129390/580f1aed-86fb-4634-812a-e83546f88010)

![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/74129390/13034196-fd2a-4d9a-9c5f-09ea51610757)

**Comment by frankedwards** [comment]
Hi,

See 0.1.22 which has added a TAILSCALED_ARGS environment variable. To use a SOCKS5 proxy and an HTTP proxy on the same port per the Tailscale example (https://tailscale.com/kb/1112/userspace-networking/):

```
/container envs add name=tailscale key=TAILSCALED_ARGS value="
--tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-
listen=localhost:1055"
```
