### ISSUE TITLE
Please mention that containers are for ARM/ARM64/X86 architectures only

### ISSUE THREAD

**Issue by MartinVonReichenberg** [Fluent-networks/tailscale-mikrotik#13]
Hello,

I just "wasted" several minutes on _"how to get Tailscale"_ on MikroTik Hex router _(which many people would be using)_ via containers and realized that there is NO 'container' support for MikroTik Hex using **MMIPS architecture**, only for the ones mentioned in the title . . .

There is literally no package among the "Extra packages" in the download section:
[MikroTik Download](https://mikrotik.com/download)

Thank you in advance . . .

**Comment by frankedwards** [comment]
Hi,

Thanks, will add some additional text in the README in the next version.

**Comment by frankedwards** [comment]
Included in 0.1.23.

**Comment by BhupiMAD** [comment]
Is there any way to run tailscale on MIPSBE ?

**Comment by MartinVonReichenberg** [comment]
> Is there any way to run tailscale on MIPSBE ? https://pkgs.tailscale.com/unstable/#static The above link shows tailscale packages for MIPS devices

This is nice, that the software supports the _'desired'_ **architecture**, but if the operating system (**MikroTik OS**) as such **does not support** it then there is no way to get it up and running.

In short:
If MikroTik OS does not provide installable package called: **`container.npk`** for the particular **architecture** **_(MIPS+-)_** then the answer is **NO**, there is **no way** . . .
