### ISSUE TITLE
How to setup to allow tailsacle to support ipv6

### ISSUE THREAD

**Issue by Shane-Meng** [Fluent-networks/tailscale-mikrotik#14]
Hi,
Thank you.It is a good product. I have pool knowlage about ipv6. Would you introduce how to setup router for ipv6 support.

**Comment by frankedwards** [comment]
Hi,

Thanks for your message.

Using IPv6 should be fairly straightforward in terms of assigning addresses and configuring static routing. The references below may assist:
https://wiki.mikrotik.com/wiki/Manual:IPv6/Address
https://wiki.mikrotik.com/wiki/Manual:IPv6/Route

Both IPv4 and IPv6 are supported by tailscale for subnet routing:
https://tailscale.com/kb/1019/subnets/

**Comment by Shane-Meng** [comment]
Thank you for your reply. 
I run `shell 0` into the container.
Then `ip -6 addr` i can see the addr assign by my isp. like 
`eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 state UP qlen 1000
    inet6 2408:8214:xxxx:yyyy:zzzz:aaaa:bbbb:bbbb/64 scope global dynamic flags 100 `
but when I try to `ping6 2001:4860:4860::8888`
·bash-5.1# ping6 2001:4860:4860::8888
PING 2001:4860:4860::8888 (2001:4860:4860::8888): 56 data bytes
ping6: sendto: Network unreachable·`

**Comment by frankedwards** [comment]
Thanks - it seems there are some issues with IPv6 on RouterOS Container... see the following forum article.
https://forum.mikrotik.com/viewtopic.php?t=197776

The release notes for RouterOS 7.11 indicated IPv6 is now supported by container. I configured the router as suggested by the article above:
Step 3:
```
/interface/bridge add name=dockers
/ip/address add address=172.17.0.1/16 interface=dockers
/ipv6/address add address=fd8d:5ad2:24:2::1 interface=dockers
/interface/veth add name="veth1" address=172.17.0.2/16,fd8d:5ad2:24:2::2/64 gateway=172.17.0.1 gateway6=fd8d:5ad2:24:2::1 
```

The container starts successfully and appears to come up with a correct IPv6 configuration, which tailscale detects.
```
bash-5.1# ip -6 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fd8d:5ad2:24:2::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::60ae:1eff:fee6:79b6/64 scope link 
       valid_lft forever preferred_lft forever
bash-5.1# ip -6 route
fd8d:5ad2:24:2::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
default via fd8d:5ad2:24:2::1 dev eth0 metric 1024 pref medium
```

However, I cannot ping fd8d:5ad2:24:2::1 from within the container.
```
bash-5.1# ping6 fd8d:5ad2:24:2::1
PING fd8d:5ad2:24:2::1 (fd8d:5ad2:24:2::1): 56 data bytes
^C
--- fd8d:5ad2:24:2::1 ping statistics ---
6 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by Shane-Meng** [comment]
It's worked. Thank you very much

**Comment by Shane-Meng** [comment]
I can ping google's DNS now follow your step. But I can't ping other my device(a phone)' by IPV6 address.

'ping fd7a:115c:a1e0:ab12:4843:cd96:6261:d429'
no any responds.

Also I notice. There show IPv6 is no in tailscale admin consule.

```
CLIENT CONNECTIVITY
Varies
No
Hairpinning
No
IPv6
No
UDP
Yes
UPnP
No
PCP
No
NAT-PMP
No
```

**Comment by frankedwards** [comment]
I believe we would need to modify the code (tailscale.sh) to enable IPv6 in the container. Unfortunately I don't have access to a publish IPv6 service to test this.

**Comment by Shane-Meng** [comment]
Very understandable. Anyway, thank you very much for your reply. And thank you for making this product available.

**Comment by Shane-Meng** [comment]
Finally, I got ipv6 working.

We need to add a route through 

```

/ipv6 route

add dst-address=fd7a:115c:a1e0:ab12::/64 gateway=dockers

```

and I temporarily disable all firewall rules for ipv6 from https://help.mikrotik.com/docs/display/ROS/Building+Your+First+Firewall. I really don't understand it and will try to edit it later when I know more about ipv6.

**Comment by frankedwards** [comment]
That's great news, thanks for sharing the info.

**Comment by Shane-Meng** [comment]
Updates. Can see ipv6=yes in the admin console now. But I still can't ping my phone with fd7a:115c:a1e0:ab12:4843::. Still some things to fix

**Comment by frankedwards** [comment]
Ok. Where is fd7a:115c:a1e0:ab12::/64 physically connected.

**Comment by Shane-Meng** [comment]
In my case. It's connected to veth2. I try add dst-address=fd7a:115c:a1e0:ab12::/64 gateway=veth2. It still not work. And looks like fd7a:115c:a1e0:ab12::/64 is the subnet of tailscale.

**Comment by Shane-Meng** [comment]
ADDRESSES
Tailscale IPv4 100.68.255.142

Tailscale IPv6 fd7a:115c:a1e0:ab12:4843
:cd96:6244:ff8e

**Comment by frankedwards** [comment]
Ok, yes so fd7a:115c:a1e0:ab12::/64 is the subnet used for Tailscale's address assignments:
https://tailscale.com/kb/1033/ip-and-dns-addresses/

I'm assuming your phone would not be running tailscale, but should be on a different subnet - e.g. just connected to bridge on the router. In the README the IPv4 equivalent is 192.168.88.0/24.

**Comment by vuducdong** [comment]
@Shane-Meng @frankedwards 

I think it must also have a route setup similar to the ipv4 side

![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/74129390/764e5907-e3b3-440a-8996-6d14135f393e)

and with ipv6 it will be:

![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/74129390/ff1bac65-7ee0-42b7-a45d-94d747280f82)

**Comment by Shane-Meng** [comment]
It's word. Thank you all. I till can't ping my phone by ipv6 address.But I can RDP to my windows now. Maybe my phone don't allow respond ping. But it can reached.
100.97.212.41   shanes-x13           mencius@     android active; direct [2408:8417:xxxx:xxxx:xxxx:xxxx:fee4:d72f]:40503, tx 214500 rx 53676
Thank you again.
