### ISSUE TITLE
update readme to included external storage

### ISSUE THREAD

**Issue by Player505** [Fluent-networks/tailscale-mikrotik#15]
I'm using a Hap ax3 and the internal storage wasn't enough to unpack the container. I looked at the logs and saw the error `no space to extract layer`.

Following this guide I set up external storage using the following command.
https://help.mikrotik.com/docs/display/ROS/Disks
```
/disk format-drive usb1 file-system=ext4 label=usb-flash mbr-partition-table=yes
```

I then had to adjust the mount command to point to the external usb.
```
/container mounts
add name="tailscale" src="usb1-part1/tailscale" dst="/var/lib/tailscale"
```

And I had to adjust the container create command to point to the external usb.
```
/container add remote-image=fluent-networks/tailscale-mikrotik:latest interface=veth1 envlist=tailscale root-dir=usb1-part1/containers/tailscale mounts=tailscale start-on-boot=yes hostname=mikrotik dns=8.8.4.4,8.8.8.8
```

**Comment by frankedwards** [comment]
Hi

Thanks for that, I'll include a link to the external storage page. 

To use external storage for unpacking see Step 6a (in your case tmpdir=usb1-part1/pull):
```
set registry-url=https://ghcr.io tmpdir=disk1/pull
```

The mount hopefully should be fine as as it only uses a small amount of storage:
```
bash-5.1#  du -sk /var/lib/tailscale/
24	/var/lib/tailscale/
```

**Comment by frankedwards** [comment]
README updated in 0.1.25
