### ISSUE TITLE
Help with setup for custom home usecase

### ISSUE THREAD

**Issue by mritunjaymusale** [Fluent-networks/tailscale-mikrotik#17]
Hi,  I have recently purchased a mikrotik with container support with little to no experience with this type of hardware and I have managed to setup the container using the default settings from readme only difference being my home network is on 192.168.3.0/24. 
I have my remote network setup at 192.168.2.0/24 and has subnet routing enabled. 
Now to the real question, is it possible for a device on 192.168.3.0/24 network communicate with a device on 192.168.2.0/24 network without installing tailscale? 
One possible solution that I can think of is to route all my traffic through the container that way all my 192.168.3.0/24 device can transparently see and interact with devices at 192.168.2.0/24 just like an PC or a phone which has tailscale installed, but can that be done using only this container without having to install tailscale on each device?

**Comment by frankedwards** [comment]
Hi,

Thanks for your message.

Certainly you can achieve what you're wanting to do using Site to Site Networking. See the wiki page:
https://github.com/Fluent-networks/tailscale-mikrotik/wiki#s2snetworking

**Comment by mritunjaymusale** [comment]
I tried it as per the guide, the issue being the other end point is a nas so can't do gateway and networking related edits there.
This is what I am getting in the logs:
![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/25117230/b1217cf4-dda2-4e01-811c-60c6119ed80e)

The apps on nas(192.168.2.0 network) never load I get a timeout error 

![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/25117230/57cf18f5-3d6c-4ef8-b584-d63fb8230422)

Any idea on what went wrong ?

**Comment by frankedwards** [comment]
Hi,

Could you post your configurations?

```
/export hide-sensitive
```

**Comment by mritunjaymusale** [comment]
Here `######` is the stuff I remove intentionally just to be safe

```
# 2023-11-14 14:13:14 by RouterOS 7.11.2
# software id = VNT9-CK04
#
# model = RB5009UPr+S+
# serial number = ##########
/container mounts
add dst=/var/lib/tailscale name=tailscale src=/tailscale
/disk
set usb1 type=hardware
set usb2 type=hardware
add parent=usb2 partition-number=1 partition-offset=512 partition-size="30 752 636 416" type=\
    partition
/interface bridge
add name=Home-Lan
add name=dockers
/interface veth
add address=172.17.0.2/16 gateway=172.17.0.1 gateway6="" name=veth1
/interface list
add name=WAN
add name=LAN
/interface wifiwave2 configuration
add country=India disabled=no hide-ssid=no mode=ap name=Home security.authentication-types=\
    wpa2-psk .wps=disable ssid=#######
/ip pool
add name=dhcp ranges=192.168.3.2-192.168.3.254
/ip dhcp-server
add address-pool=dhcp interface=Home-Lan name=dhcp1
/container
add dns=1.1.1.1,8.8.8.8 envlist=tailscale hostname=mikrotik interface=veth1 logging=yes \
    mounts=tailscale root-dir=/containers/tailscale start-on-boot=yes
/container config
set registry-url=https://ghcr.io tmpdir=usb2-part1/pull
/container envs
add key=PASSWORD name=tailscale value=########
add key=AUTH_KEY name=tailscale value=\
    ######################################
add key=ADVERTISE_ROUTES name=tailscale value=192.168.3.0/24
add key=CONTAINER_GATEWAY name=tailscale value=172.17.0.1
add key=TAILSCALE_ARGS name=tailscale value="--accept-routes --snat-subnet-routes=false"
/interface bridge port
add bridge=Home-Lan interface=ether2
add bridge=Home-Lan interface=ether3
add bridge=Home-Lan interface=ether4
add bridge=Home-Lan interface=ether5
add bridge=Home-Lan interface=ether6
add bridge=Home-Lan interface=ether7
add bridge=Home-Lan interface=ether8
add bridge=Home-Lan interface=sfp-sfpplus1
add bridge=dockers interface=veth1
/interface list member
add interface=ether1 list=WAN
add interface=Home-Lan list=LAN
/interface wifiwave2 capsman
set enabled=yes package-path="" require-peer-certificate=no upgrade-policy=none
/interface wifiwave2 provisioning
add action=create-dynamic-enabled disabled=no master-configuration=Home
/ip address
add address=192.168.3.1/24 interface=Home-Lan network=192.168.3.0
add address=172.17.0.1/16 interface=dockers network=172.17.0.0
/ip dhcp-client
add interface=ether1 use-peer-dns=no
/ip dhcp-server network
add address=192.168.3.0/24 gateway=192.168.3.1 netmask=24
/ip dns
set allow-remote-requests=yes use-doh-server=https://1.1.1.1/dns-query verify-doh-cert=yes
/ip dns static
add address=104.16.249.249 name=cloudflare-dns.com
/ip firewall filter
add action=accept chain=input comment="accept established,related,untracked"
add action=drop chain=input comment="drop invalid"
add action=accept chain=input comment="accept ICMP" protocol=icmp
add action=accept chain=input comment="accept to local loopback(for CAPsMAN)" dst-address=\
    127.0.0.1
add action=drop chain=input comment="drop all not coming from LAN" in-interface-list=!LAN
add action=accept chain=forward comment="accept in ipsec policy"
add action=accept chain=forward comment="accept out ipsec policy"
add action=fasttrack-connection chain=forward comment=fasttrack hw-offload=yes
add action=accept chain=forward comment="accept, established, realated, untracked"
add action=drop chain=forward comment="drop invalid"
add action=drop chain=forward comment="drop all from WAN not DSTNATed" in-interface-list=WAN
/ip firewall nat
add action=masquerade chain=srcnat out-interface-list=WAN
/ip route
add dst-address=100.64.0.0/8 gateway=172.17.0.2
add dst-address=192.168.2.0/24 gateway=172.17.0.2
/system clock
set time-zone-name=Asia/Kolkata
/system note
set show-at-login=no
```

**Comment by frankedwards** [comment]
Thanks... sorry are saying you don't have a router on the 192.168.2.0/24 network.

You would need a router at each site per the Wiki example.

**Comment by mritunjaymusale** [comment]
I have router at 192.168.3.0/24 network and 192.168.2.0/24 is normal network with isp router but I have enabled subnet routing using tailscale's docker/container image  on a nas. 
So is it not possible for 192.168.3.0/24 tailscale container to push the traffic to the 192.168.2.0/24 nas container?

**Comment by frankedwards** [comment]
HI,

Your configuration above looks OK. Just checking you have:
* setup the other tailscale subnet router per https://tailscale.com/kb/1214/site-to-site/
* enabled the subnet routes in the Tailscale console for both devices
* added a route at the other end pointing 192.168.3.0/24 to the remote subnet router LAN address

Also the ping test command above should be:
```
/ping 192.168.2.173 src-address=192.168.3.1
```

**Comment by mritunjaymusale** [comment]
So something like this on 192.168.2.0/24? it's an asus router 

![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/25117230/4f997455-2f3e-4878-b694-0fef7af255aa)

**Comment by frankedwards** [comment]
Yes.

**Comment by mritunjaymusale** [comment]
Nope didn't work, I think it has to be a mikrotik router on the other end, closing for now, in future will try this again with both routers setup as you mentioned and if doesn't work i'll reopen the issue
