### ISSUE TITLE
Add autoupdate feature

### ISSUE THREAD

**Issue by mritunjaymusale** [Fluent-networks/tailscale-mikrotik#18]
Can you add [this](https://tailscale.com/kb/1067/update#auto-updates) feature to the container image?
That way the tailscale app internally can auto-update itself. 
This is how I do currently:
![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/25117230/206cd752-7696-447d-b673-b0cbc767b3df)

Since it's non package manager installation, I would suggest in the update.rsc you add the command from the image and an option to stop and start the container after update is complete, in order to get tailscaled to restart properly

**Comment by frankedwards** [comment]
Hi,

Thanks for the suggestion. I think this would be possible if the docker image is built using the Alpine package to enable the auto-update feature to work.

Then we would add an environment variable, e.g. AUTO_UPDATE to run ```tailscale set --auto-update``` in ```tailscale.sh```

**Comment by mritunjaymusale** [comment]
Yes, that would be better

**Comment by frankedwards** [comment]
It seems as though tailscale relies on packages provided via Alpine - see [here](https://github.com/tailscale/tailscale/issues/3790), so I don't think auto-update will be possible.

The next best option as you suggest is to add an environment variable UPDATE_TAILSCALE that will run ```tailscale update --yes``` prior to starting tailscaled & tailscale.

In this way if a new tailscale version was available, starting and stopping the container would apply the update.

**Comment by frankedwards** [comment]
See 0.1.26
