### ISSUE TITLE
Permission denied when shell container

### ISSUE THREAD

**Issue by jozsoka2222** [Fluent-networks/tailscale-mikrotik#19]
I got permission denied error when i shell container, what can i do?
![image](https://github.com/Fluent-networks/tailscale-mikrotik/assets/36086735/c7df5e56-0c69-4db4-9b51-497bb7414332)

**Comment by frankedwards** [comment]
Hi,

I don't think /root/.bashrc is included in the container image...

Could you show the output of
# ls -la /root

**Comment by jozsoka2222** [comment]
I use nfs, because thats's not worked i used smb, with rose storage package because i don't have usb port on hap ac2, and when i use smb solved the permission problem, but rose-storage has a lot of bug, for example write some file and error in extracting, maybe smb mount inside container help this problem?

**Comment by frankedwards** [comment]
Closing as unrelated to the project.
