### ISSUE TITLE
Can't build image

### ISSUE THREAD

**Issue by dvelopin** [Fluent-networks/tailscale-mikrotik#2]
I was hoping you could help me out. I am trying to build an image for Tailscale on my RB4011, but am having issues after running ./build.sh.

It runs through a long process and downloads a ton of things, but then exits with the following:

```
#0 70.61 tailscale.com/net/tstun
#0 71.01 # tailscale.com/net/tstun
#0 71.01 net/tstun/wrap.go:130:16: undefined: atomic.Pointer
#0 71.01 note: module requires Go 1.19
------
error: failed to solve: executor failed running [/bin/sh -c GOARCH=$TARGETARCH go install -ldflags="      -X tailscale.com/version.Long=$VERSION_LONG       -X tailscale.com/version.Short=$VERSION_SHORT       -X tailscale.com/version.GitCommit=$VERSION_GIT_HASH"       -v ./cmd/tailscale ./cmd/tailscaled]: exit code: 2
```

I am on macOS Ventura which may very well have something to do with it, but I have tried running Parallels with Ubuntu, Debain, even a VM of macOS 12, but keep getting issues on build.

I need the same image you have for the hAP ac 3. Mine is also an ARM based chip.

Do you have any ideas? I'd love to play with this.

**Comment by frankedwards** [comment]
Hi

Thanks for letting me know, it looks like tailscale now requires go 1.19 to build.

I've updated the build stage base image in 0.1.4 and this appears to resolve the issue.

Let me know if this generates a tailscale.tar file via build.sh for you.

Regards

Frank

**Comment by dvelopin** [comment]
Hey Frank,

Thank you so much for this. It worked for me now! Excited to try this out.
