### ISSUE TITLE
Use OAuth client (=not constantly having to renew AUTH_KEY every 3 months)

### ISSUE THREAD

**Issue by shadow1runner** [Fluent-networks/tailscale-mikrotik#20]
Tailscale features OAuth clients which, unlike the expiring auth keys, don't need to be renewed constantly.
For examle, their [Github Action](https://github.com/tailscale/github-action/blob/main/action.yml#L115) is making use of them.

Things I tried were:
* creating a [new OAuth Client](https://login.tailscale.com/admin/settings/oauth) with `Devices: write` scope (also tried with `All: write`, did not change the issue)
  * make sure to specify a tag here, e.g. `tag:mikrotik`
* copied the client id and client secret
* on Mikrotik: 
  * changed the `AUTH_KEY` env variable to e.g. `tskey-client-this-is-not-real?preauthorized=true&ephemeral=true`
  * added the OAuth tag to `TAILSCALE_ARGS` env variable, e.g. `--accept-routes --advertise-exit-node --advertise-tags=tag:mikrotik`
* (re-)started the container and observed (1) the logs (`logging=yes`); also, I've observed (2) the [Tailscale OAuth logs](https://login.tailscale.com/admin/logs) and now comes the actual issue: from (2) everything looks good, as far as I can tell, but from (1) I see constant retries, complaining that `backend error: invalid key: API key <redacted> not valid` (which also spam (2), but I can't see anything suspicions in (2).

![2024-01-13_11-52](https://github.com/Fluent-networks/tailscale-mikrotik/assets/3902045/48f3c23a-dc0c-4833-8b2e-a3dbfe22a1b2)

Do you happen to have experience with Tailscale OAuth Clients (on Mikrotik)?
Anyway, thanks a lot for all your effort!

**Comment by frankedwards** [comment]
Thanks for raising this issue. You were on the right track - it looks like missing quotes in tailscale.sh was causing an issue with Oauth registration.

If you could test using 0.1.27 - I was able to register a new node using OAuth credentials.

**Comment by hwo-wd** [comment]
Thank you very much!
Just tried it and it's working like a charm -- no more auth key updating every 3 months 👍
