### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by NewsGuyTor** [Fluent-networks/tailscale-mikrotik#21]
I think the all the new features like easy updates and OAuth should be in the readme instead of the old procedures of expiring keys and update.rsc.

**Comment by frankedwards** [comment]
In terms of updates, the TAILSCALE_UPDATE variable provides a way to update the tailscale binaries in the current container version, but updating the container version would require a manual or automated container upgrade. For example, Tailscale regularly increments the Alpine OS version used, which requires a new container image.

Using OAuth or auth keys is a user choice for any particular machine. Auth keys have not been deprecated and you can use either method, or a mix of both in any tailnet.
