### ISSUE TITLE
No license present

### ISSUE THREAD

**Issue by mjohnson9** [Fluent-networks/tailscale-mikrotik#22]
Hello! Please add a license to your code. Under most copyright law, without a clear license, you provide no rights to those receiving your code. Depending on the jurisdiction of the recipient, simply downloading your code and using the Dockerfile to build a container may constitute copyright infringement[^1].

The header of Dockerfile[^2] seems to indicate that you reused code from the Tailscale project which was licensed under a BSD license. Generally, derivatives of BSD-licensed code must be licensed the same as the code they derived[^3], so you'll likely want to use the same license as Tailscale[^4].

[^1]: https://www.gnu.org/licenses/license-list.en.html#NoLicense
[^2]: https://github.com/Fluent-networks/tailscale-mikrotik/blob/3112ea2b100a5fce99f95e25bc2480a5bad84ceb/Dockerfile#L1-L3
[^3]: https://github.com/tailscale/tailscale/blob/a633a3071158b7e55adf8087d1e68aac986a6bc8/LICENSE#L8-L9
[^4]: https://opensource.stackexchange.com/a/2835

**Comment by frankedwards** [comment]
See 0.1.28

**Comment by mjohnson9** [comment]
Thank you!
