### ISSUE TITLE
IP forwarding setup failing in the container

### ISSUE THREAD

**Issue by mLupine** [Fluent-networks/tailscale-mikrotik#23]
I've just set up the container in my home network and noticed that while I can connect to the container shell from other devices in my Tailscale network, I can't access the TS network from devices in my home network. Traceroute shows that packets reach the container and get stuck there:
```
traceroute to 100.91.14.11 (100.91.14.11), 64 hops max, 52 byte packets
 1  192.168.0.1 (192.168.0.1)  3.070 ms  2.043 ms  3.423 ms
 2  100.79.211.111 (100.79.211.111)  5.508 ms  3.917 ms  3.819 ms
 3  * * *
```

I've connected to the container and executed `tailscale status` to check what's happening. The healthcheck there reports the following issue:
```
# Health check:
#     - router: adding [-i tailscale0 -j MARK --set-mark 0x40000/0xff0000] in v4/filter/ts-forward: running [/sbin/iptables -t filter -A ts-forward -i tailscale0 -j MARK --set-mark 0x40000/0xff0000 --wait]: exit status 1: iptables: Invalid argument. Run `dmesg' for more information.
```

While it doesn't seem possible to access dmesg there, I verified that iptables are, indeed, quite empty:
```
rt1:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ts-input   all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ts-forward  all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain ts-forward (1 references)
target     prot opt source               destination

Chain ts-input (1 references)
target     prot opt source               destination
RETURN     all  --  100.115.92.0/23      anywhere
DROP       all  --  100.64.0.0/10        anywhere
ACCEPT     all  --  anywhere             anywhere
```

Let me know if I can provide any more data to help debug the issue.

Thanks!

**Comment by mLupine** [comment]
Hi, 

that's correct. I can reach other Tailscale devices from within the Tailscale container, and seemingly home network devices from other Tailscale-connected devices, but traffic from non-Tailscale devices on the home network doesn't reach the Tailscale network.

**Comment by frankedwards** [comment]
Hi,

That's by design... see https://tailscale.com/kb/1019/subnets

Subnet routers act as a gateway, relaying traffic from your Tailscale network onto your physical subnet. You would need to install Tailscale on any device intending to access the Tailnet.

Otherwise you would have non-authenticated devices accessing your secure Tailnet.

**Comment by mLupine** [comment]
Hm, in that case, what's the purpose of the route to the Tailscale network?

```
/ip/route/add dst-address=100.64.0.0/10 gateway=172.17.0.2
```

**Comment by frankedwards** [comment]
Routing return traffic from the non-Tailscale devices back to the tailnet.

For example, if a tailscale host pings a non-tailscale device on the home network, the non-tailscale device sees the source address as 100.x.x.x and returns an ICMP response via the default gateway on your router. The above route enables the router to send the response packet to the container as the next hop.
