### ISSUE TITLE
Local Build & Deploy (Step 6b) not working

### ISSUE THREAD

**Issue by schmittfelix** [Fluent-networks/tailscale-mikrotik#24]
Hi,
i've been struggling trying to build, upload and deploy this image locally.

I've narrowed it down to the fact that [since 7.10](https://mikrotik.com/download/changelogs#show-tab-tree_2-id-5a989a5d00ba0820921931d9826b8741) the Mikrotik Container implementation supports the OCI manifest format for remote images, but not for uploaded image.tar files. Trying to use an OCI-formatted image.tar file results in an extraction error.
What's problematic is that it's increasingly hard to build and export images in the legacy Docker Manifest v2s2 format ([eg thanks to this behaviour change](https://github.com/docker/buildx/pull/1813#issuecomment-1553895407)) but Mikrotik Containers can't work with anything else not registry-based.

So far I've not been able to successfully build and export a valid v2s2-formatted image to use with the local file option in ROS.

Is it possible for you to share how you build the images within the package releases?

Time permitted, I'll also open a Forum Thread as well as a Mikrotik Support Ticket/Feature request to support the OCI format for local image.tar files.

I'm open for any suggestions to help get the building/exporting steps right!

Thanks in advance!

**Comment by frankedwards** [comment]
Hi,

Currently have Docker Desktop 4.27.2 (137060) installed on MacOS. To generate the tar file - per the README I'm running ```build.sh```, then uploading to a CHR image running RouterOS 7.13.4.

Does the info below assist?

$ docker buildx inspect
Name:          admiring_borg
Driver:        docker-container
Last Activity: 2024-02-15 05:18:41 +0000 UTC

Nodes:
Name:      admiring_borg0
Endpoint:  desktop-linux
Status:    running
Buildkit:  v0.12.5
Platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
Labels:
 org.mobyproject.buildkit.worker.executor:         oci
 org.mobyproject.buildkit.worker.hostname:         1390c2af2c5a
 org.mobyproject.buildkit.worker.network:          host
 org.mobyproject.buildkit.worker.oci.process-mode: sandbox
 org.mobyproject.buildkit.worker.selinux.enabled:  false
 org.mobyproject.buildkit.worker.snapshotter:      overlayfs
