### ISSUE TITLE
--accept-routes is false

### ISSUE THREAD

**Issue by dimmuboy** [Fluent-networks/tailscale-mikrotik#25]
Please just add to wiki that it's necessary to set `--accept-routes=True` in `TAILSCALE_ARGS` for proper working.
Otherwise I got following message:

```
mikrotik:/# tailscale status
...
#     - Some peers are advertising routes but --accept-routes is false

```

I found solution here:
https://github.com/tailscale/tailscale/issues/2053

**Comment by frankedwards** [comment]
See 0.1.30. Added note in README for TAILSCALE_ARGS variable.
