### ISSUE TITLE
Make PLATFORM dynamic

### ISSUE THREAD

**Issue by NewsGuyTor** [Fluent-networks/tailscale-mikrotik#6]
It seems really dumb that PLATFORM is hard-coded to be the 32 bit arm7. 

It should be dynamic based on the hardware, or at least arm64.

**Comment by frankedwards** [comment]
Hi

Thanks for your feedback.

The PLATFORM variable is intended to be configured for the target architecture as per the build instructions, prior to running build.sh.

Both arm7 and arm64 are supported by multiple Mikrotik router models.. changing it to arm64 is fine.

Regards

Frank

**Comment by NewsGuyTor** [comment]
So build.sh is not used in step 6.a (Container registry)?

For people who aren't super familiar like me with Docker, I don't know what files "/container add remote-image=fluent-networks/tailscale-mikrotik:latest" uses from this repo. 

If it doesn't use build.sh that should be clarified in the README, and if it uses it I don't see how you can change the PLATFORM when you pull the file directly.

**Comment by frankedwards** [comment]
Hi,

That's right, build.sh is not required in Step 6a. 

The ghcr.io repo contains linux/arm/v7,  linux/arm64 and  linux/amd64 images. When you issue the pull **/container add** command, the router requests its required architecture. 

You can see these images at:
https://github.com/orgs/Fluent-networks/packages/container/package/tailscale-mikrotik
... click on OS/Arch tab.

The same process as build.sh is used to create & upload these images, just using a multi-architecture build script. I guess I could include that, I just thought it might confuse people who want to create a local image.

Regards

Frank

**Comment by frankedwards** [comment]
I've updated README to clarify the build step is only required if Configuration Step 6b is being used.
