### ISSUE TITLE
Using headscale instead of tailscale

### ISSUE THREAD

**Issue by rumman-cst** [Fluent-networks/tailscale-mikrotik#9]
Hi, I am trying to use this with self-hosted headscale instance. Do you happen to have any information / experience using headscale with this container?
When I run this with headscale, the container restarts and "invalid key: unable to validate API key" can be seen in the logs. I can verify that my API key is correct.

**Comment by frankedwards** [comment]
Hi,

No I haven't tried configuring it for use with headscale. Expect it would require some modifications to tailscale.sh, which currently has api.tailscale.com hardwired for API access.

I'll check with the headscale documentation.

**Comment by frankedwards** [comment]
Hi,

if you could test out 0.1.17 with your headscale server that would be great. The README has been updated with how to configure for Headscale.
